# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/alarm_32px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 951, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 331, 301))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 369, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsButton = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/settings_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon1)
        self.settingsButton.setIconSize(QtCore.QSize(24, 24))
        self.settingsButton.setObjectName("settingsButton")
        self.horizontalLayout.addWidget(self.settingsButton)
        self.aboutButton = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/info_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon2)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout.addWidget(self.aboutButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(430, 0, 530, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.autoModeButton = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget_2)
        self.autoModeButton.setCheckable(True)
        self.autoModeButton.setChecked(True)
        self.autoModeButton.setObjectName("autoModeButton")
        self.horizontalLayout_2.addWidget(self.autoModeButton)
        self.manualModeButton = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget_2)
        self.manualModeButton.setCheckable(True)
        self.manualModeButton.setChecked(False)
        self.manualModeButton.setObjectName("manualModeButton")
        self.horizontalLayout_2.addWidget(self.manualModeButton)
        self.amModeButton = QtWidgets.QCommandLinkButton(self.horizontalLayoutWidget_2)
        self.amModeButton.setCheckable(True)
        self.amModeButton.setObjectName("amModeButton")
        self.horizontalLayout_2.addWidget(self.amModeButton)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(350, 170, 331, 301))
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(690, 170, 271, 301))
        self.tableWidget_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 331, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 150, 331, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(690, 150, 271, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(600, 480, 251, 101))
        self.groupBox.setObjectName("groupBox")
        self.manualRingButton = QtWidgets.QPushButton(self.groupBox)
        self.manualRingButton.setGeometry(QtCore.QRect(10, 20, 231, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/alarm_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manualRingButton.setIcon(icon3)
        self.manualRingButton.setIconSize(QtCore.QSize(24, 24))
        self.manualRingButton.setObjectName("manualRingButton")
        self.manualLightButton = QtWidgets.QPushButton(self.groupBox)
        self.manualLightButton.setEnabled(False)
        self.manualLightButton.setGeometry(QtCore.QRect(10, 60, 231, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/light_on_24px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manualLightButton.setIcon(icon4)
        self.manualLightButton.setIconSize(QtCore.QSize(24, 24))
        self.manualLightButton.setObjectName("manualLightButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(860, 480, 101, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.statusR = QtWidgets.QLabel(self.groupBox_2)
        self.statusR.setGeometry(QtCore.QRect(50, 20, 32, 32))
        self.statusR.setMaximumSize(QtCore.QSize(32, 32))
        self.statusR.setObjectName("statusR")
        self.statusL = QtWidgets.QLabel(self.groupBox_2)
        self.statusL.setGeometry(QtCore.QRect(50, 60, 32, 32))
        self.statusL.setMaximumSize(QtCore.QSize(32, 32))
        self.statusL.setObjectName("statusL")
        self.iconRing = QtWidgets.QLabel(self.groupBox_2)
        self.iconRing.setGeometry(QtCore.QRect(10, 20, 32, 32))
        self.iconRing.setMaximumSize(QtCore.QSize(32, 32))
        self.iconRing.setText("")
        self.iconRing.setPixmap(QtGui.QPixmap("images/notification_32px.png"))
        self.iconRing.setObjectName("iconRing")
        self.iconLight = QtWidgets.QLabel(self.groupBox_2)
        self.iconLight.setGeometry(QtCore.QRect(10, 60, 32, 32))
        self.iconLight.setMaximumSize(QtCore.QSize(32, 32))
        self.iconLight.setText("")
        self.iconLight.setPixmap(QtGui.QPixmap("images/light_on_32px.png"))
        self.iconLight.setObjectName("iconLight")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(630, 110, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 560, 311, 16))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bell Manager"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.settingsButton.setText(_translate("MainWindow", "Настройки"))
        self.aboutButton.setText(_translate("MainWindow", "О программе"))
        self.autoModeButton.setToolTip(_translate("MainWindow", "В автоматическом режиме система сама управляет звонками и освещением по заданному расписанию"))
        self.autoModeButton.setText(_translate("MainWindow", "Авто"))
        self.manualModeButton.setToolTip(_translate("MainWindow", "В ручном режиме звонок и освещение управляются только кнопками ручного управления"))
        self.manualModeButton.setText(_translate("MainWindow", "Ручной"))
        self.amModeButton.setToolTip(_translate("MainWindow", "В полуавтоматическом режиме звонки подаются по расписанию, освещение в ручном режиме"))
        self.amModeButton.setText(_translate("MainWindow", "Полуавтомат"))
        self.label_2.setText(_translate("MainWindow", "Текущее расписание:"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_3.setText(_translate("MainWindow", "1 смена"))
        self.label_4.setText(_translate("MainWindow", "2 смена"))
        self.label_5.setText(_translate("MainWindow", "Освещение"))
        self.groupBox.setTitle(_translate("MainWindow", "Ручное управление"))
        self.manualRingButton.setText(_translate("MainWindow", "Включить звонок"))
        self.manualLightButton.setText(_translate("MainWindow", "Включить/выключить освещение"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Текущий статус"))
        self.statusR.setText(_translate("MainWindow", "R"))
        self.statusL.setText(_translate("MainWindow", "L"))
        self.label_6.setText(_translate("MainWindow", "Режим энергосбережения"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
